Update 'Message' description
NCATSTranslator/ReasonerAPI pull request #168
Opened 2020-10-22 04:56 UTC by brettasmi

This updates the `components/schemas/Message` description ahead of the 1.0 release.

2020-10-28 03:43 UTC, edeutsch requested changes
Would be good to mention the KnowledgeGraph in the description. The three things are the QueryGraph, the KnowledgeGraph, and the Results (which are the answers that bind the KG nodes and edges to QG nodes and edges)

2020-10-29 16:23 UTC, CaseyTa commented
In the knowledge_graph description, I think we've removed support for remote knowledge graphs. Can anyone else confirm?

2020-10-29 16:25 UTC, patrickkwang commented
> In the knowledge_graph description, I think we've removed support for remote knowledge graphs. Can anyone else confirm?

Confirmed.

2020-11-05 17:14 UTC, CaseyTa commented on TranslatorReasonerAPI.yaml
> +        property. The content of these properties is context-dependent
> any answers in the results property, and a mapping of response nodes
>         and edges to their QueryGraph counterparts in the knowledge_graph
>         property

This wording is a little confusing to me. It sounds like the results property and the mapping of response nodes and edges are separate things, when I believe you're referring to the same thing.

2020-11-12 14:25 UTC, CaseyTa requested changes
There's an extra "and edges" in the description for `knowledge_graph`. 

Otherwise, I approve of these changes.

2020-11-12 14:25 UTC, CaseyTa commented on TranslatorReasonerAPI.yaml
> +            and edges in the thought graph corresponding to the message
There's an extra "and edges" here.

2020-11-12 17:31 UTC, CaseyTa approved these changes

2020-11-19 16:49 UTC, edeutsch approved these changes

2020-11-19 16:54 UTC, patrickkwang approved these changes

2020-11-20 05:07 UTC, vdancik approved these changes

2020-11-20 17:27 UTC, rtroper approved these changes

2020-11-21 01:22 UTC, brettasmi commented
Thanks for the feedback everyone. I think I need @edeutsch, @patrickkwang or someone else with privileges to merge this.

2020-11-21 02:02 UTC, merged