Update 'Result' object description
NCATSTranslator/ReasonerAPI pull request #169
Opened 2020-10-22 15:55 UTC by rtroper

2020-10-23 18:30 UTC, ehinderer approved these changes

2020-10-28 03:39 UTC, edeutsch approved these changes

2020-10-29 16:29 UTC, CaseyTa commented
Suggestion: A Result object specifies **the nodes and edges in the** knowledge graph that satisfy the structure or conditions of a user-submitted query graph.

2020-10-29 16:33 UTC, patrickkwang requested changes
> Suggestion: A Result object specifies **the nodes and edges in the** knowledge graph that satisfy the structure or conditions of a user-submitted query graph.

-- @CaseyTa

2020-10-29 19:48 UTC, rtroper commented
> Suggestion: A Result object specifies **the nodes and edges in the** knowledge graph that satisfy the structure or conditions of a user-submitted query graph.

Good suggestion. I've made the change.

2020-10-29 19:50 UTC, edeutsch approved these changes

2020-11-02 16:32 UTC, merged