Update documentation for Attribute object
NCATSTranslator/ReasonerAPI pull request #172
Opened 2020-10-29 03:04 UTC by vdancik

2020-11-02 16:20 UTC, edeutsch requested changes
Seems pretty good, but please fix the too-long-lines. Max line length is 79 chars. Also on line 370 'referably' -> 'preferably'

2020-11-05 16:52 UTC, CaseyTa approved these changes

2020-11-12 06:52 UTC, edeutsch approved these changes
looks good, thanks!

2020-11-12 13:49 UTC, CaseyTa requested changes

2020-11-12 13:49 UTC, CaseyTa commented on TranslatorReasonerAPI.yaml
> +            identifier does not exist, enter avdescriptive phrase here and
Minor typo with "avdescriptive"

2020-11-12 23:59 UTC, vdancik commented on TranslatorReasonerAPI.yaml
> +            identifier does not exist, enter avdescriptive phrase here and
typo is now fixed

2020-11-13 02:26 UTC, CaseyTa approved these changes

2020-11-19 16:42 UTC, bill-baumgartner approved these changes

2020-11-19 17:01 UTC, patrickkwang approved these changes

2020-11-21 02:03 UTC, merged