Add simple Message example
NCATSTranslator/ReasonerAPI pull request #175
Opened 2020-11-05 17:59 UTC by patrickkwang

2020-11-12 07:08 UTC, edeutsch requested changes
Seems okay, except can we make n0 specifically Ebola? The QueryGraph as written is too vague to be answerable. If n0 is specifically MONDO:0005737, the example makes a whole lot more sense.

2020-11-12 16:37 UTC, edeutsch approved these changes
looks good, thanks!

2020-11-12 17:36 UTC, bill-baumgartner approved these changes

2020-11-19 16:44 UTC, CaseyTa approved these changes

2020-11-19 18:09 UTC, vdancik approved these changes

2020-11-21 02:03 UTC, merged