Edge.relation should be an ontology CURIE
NCATSTranslator/ReasonerAPI pull request #176
Opened 2020-11-05 23:33 UTC by RichardBruskiewich

If TRAPI and the Biolink Model are to remain closely aligned at the fundamental semantic level, then the `Edge.relation` property of a KnowledgeGraph absolutely needs to be a CURIE dereferencing a formal external 3rd party ontology class definition. 

I believe this to be a release 1.0 'bug' in the TRAPI schema.

2020-11-05 23:38 UTC, TomConlin commented
+1

2020-11-05 23:59 UTC, TomConlin commented
Has there been any discussion of  categories  for edges?  
"lower level type of an edge" is getting pretty close to a meaning of category

2020-11-06 02:56 UTC, RichardBruskiewich commented
> 
> 
> Has there been any discussion of categories for edges?
> "lower level type of an edge" is getting pretty close to a meaning of category

Actually, edges have `predicate` (formerly `edge_label`) already. I think the TRAPI comment about 'lower level' is a bit misleading. All that it meant by this is the "original (predicate) relationship coming from the (external, non-Translator) knowledge source" for that 'relationship edge'

Thus the `predicate` slot already has the analogous role for relationship edges that `category` slot has for concept nodes.

2020-11-06 06:34 UTC, TomConlin commented
ah so lower level in this case is approximately  'original'

2021-05-05 21:31 UTC, vdancik commented
I believe that this should stay as currently documented - use of CURIEs for relations should be encouraged, but not formally required.

2021-05-26 16:51 UTC, vdancik requested changes
I would keep `type: string` and the following description:

"The relationship type term of this edge, originally specified by, or curated by inference from, the original source of knowledge. This should generally be specified as predicate ontology CURIE."

2021-05-26 20:55 UTC, CaseyTa commented
> I would keep `type: string` and the following description:
> 
> "The relationship type term of this edge, originally specified by, or curated by inference from, the original source of knowledge. This should generally be specified as predicate ontology CURIE."

And perhaps also change the example to a CURIE

2021-06-03 13:48 UTC, ehinderer approved these changes

2021-07-22 17:49 UTC, edeutsch commented
(Q)Edge.relation was previously removed as not relevant, so this PR is not moot and is being withdrawn after discussion on 2021-07-22

2021-07-22 17:49 UTC, closed without merging