'score' property  added to EdgeBinding
NCATSTranslator/ReasonerAPI pull request #181
Opened 2020-11-17 22:20 UTC by RichardBruskiewich

2020-11-19 18:05 UTC, vdancik requested changes
Not necessary as a separate property, can be provided as an edge attribute.

2020-11-19 18:15 UTC, edeutsch commented
We might want to add this in the future, but let's see what the EPC group comes up with

2020-11-19 21:24 UTC, ehinderer approved these changes

2021-07-15 20:45 UTC, vgardner-renci commented
https://github.com/NCATSTranslator/ReasonerAPI/pull/247 accomplished this

2021-07-15 20:45 UTC, closed without merging