Adding documentation for QNode
NCATSTranslator/ReasonerAPI pull request #182
Opened 2020-11-19 17:00 UTC by MarkDWilliams

2020-11-19 21:17 UTC, ehinderer requested changes
Typo in the first sentence, should be "...used **to** represent an entity..." Otherwise fine I think.

2020-11-20 04:58 UTC, vdancik approved these changes

2020-11-20 18:01 UTC, rtroper commented on TranslatorReasonerAPI.yaml
> +        of the QNode will be returned is the Results.
Another little typo: Did you mean to say "...will be returned [in] the Results"?

2020-12-03 18:16 UTC, patrickkwang requested changes

2020-12-03 18:16 UTC, patrickkwang commented on TranslatorReasonerAPI.yaml
> +        query. If a CURIE is not specified, any nodes matching the type
```suggestion
        query. If a CURIE is not specified, any nodes matching the category
```

2020-12-03 18:40 UTC, patrickkwang approved these changes

2020-12-03 18:53 UTC, MarkDWilliams commented
I believe the typos and suggestions have all been corrected/made.

2020-12-03 21:19 UTC, edeutsch approved these changes

2020-12-10 17:17 UTC, merged