Add biolink-model version to x-translator
NCATSTranslator/ReasonerAPI pull request #223
Opened 2021-03-24 21:04 UTC by vdancik

2021-03-25 06:23 UTC, edeutsch approved these changes

2021-03-25 13:38 UTC, patrickkwang commented
Looks like branching got wonky here. This may just need to be rebased onto v1.1.x.

2021-03-25 15:55 UTC, ehinderer approved these changes

2021-03-25 17:00 UTC, bill-baumgartner approved these changes

2021-03-26 00:09 UTC, colleenXu commented on TranslatorReasonerAPI.yaml
> +    biolink_model_version: INSERT-BIOLINK-MODEL-VERSION-HERE
Change this to match translator_extension schema?

The translator_extension schema currently uses [biolink-version](https://github.com/NCATSTranslator/translator_extensions/blob/62755f92c82d6aafa2ae55c394434640ebb9a0dd/x-translator/smartapi_x-translator_schema.json#L52) as the property name, with acceptable values following the official biolink releases: so versions like '1.6.1', '1.6.0'...

2021-03-26 00:11 UTC, colleenXu commented on TranslatorReasonerAPI.yaml
> +    component: INSERT-EITHER-ARA-OR-KP-HERE
Team is not correctly structured here, and the component description doesn't include all the actual allowed values. See #217 for my recommendations of how to specify x-trapi and x-translator.

2021-03-26 00:12 UTC, colleenXu requested changes
See my comments for the changes I requested/issues I have.

2021-03-31 20:55 UTC, merged