Specificity of /meta_knowledge_graph
NCATSTranslator/ReasonerAPI pull request #254
Opened 2021-05-27 19:00 UTC by cbizon

Based on the 5/25 Architecture call, the prevailing opinion was that the meta knowledge graph endpoint should return a minimal specific set of catetgories/predicates and rely on ARAs to understand the inference rules and make sense of them.

2021-05-27 20:11 UTC, edeutsch requested changes
This change seems pretty well stated to me, but checks are failing because of line length limit overruns and other formatting issues.

2021-06-01 14:21 UTC, cbizon commented
OK, thanks for pointing that out @edeutsch, formatting is passing now.

2021-06-01 18:05 UTC, edeutsch approved these changes

2021-06-01 18:25 UTC, bill-baumgartner approved these changes

2021-06-01 18:30 UTC, newgene approved these changes

2021-06-01 18:37 UTC, andrewsu approved these changes

2021-06-02 17:10 UTC, rtroper approved these changes

2021-06-03 17:14 UTC, marcdubybroad approved these changes

2021-06-03 17:17 UTC, CaseyTa approved these changes

2021-06-03 17:17 UTC, vdancik approved these changes

2021-06-08 17:33 UTC, merged