Fix documentation to reflect prior removal of 'relation'
NCATSTranslator/ReasonerAPI pull request #285
Opened 2021-08-17 23:24 UTC by edeutsch

2021-08-19 17:20 UTC, vdancik approved these changes

2021-08-19 17:38 UTC, kshefchek approved these changes

2021-08-24 00:35 UTC, marcdubybroad approved these changes

2021-08-24 15:16 UTC, vdancik approved these changes

2021-08-24 15:23 UTC, rtroper approved these changes

2021-08-24 17:01 UTC, bill-baumgartner requested changes
These change looks good. I suggest an additional minor change to the final sentence in the description: remove references to 'class' and 'subclass of', e.g.,  

> ... an exact match to the given QEdge predicate term, or to a term that is a descendant of the QEdge predicate term.

In OWL, the Biolink predicates that could belong to a QEdge are not referred to as *classes* but as *object properties* so it is potentially confusing to use 'class' and 'subclass of' here IMO.

2021-08-30 16:47 UTC, edeutsch commented
> 
> 
> These change looks good. I suggest an additional minor change to the final sentence in the description: remove references to 'class' and 'subclass of', e.g.,
> 
> > ... an exact match to the given QEdge predicate term, or to a term that is a descendant of the QEdge predicate term.
> 
> In OWL, the Biolink predicates that could belong to a QEdge are not referred to as _classes_ but as _object properties_ so it is potentially confusing to use 'class' and 'subclass of' here IMO.

yes, this seems reasonable. I have updated the PR to reflect this.

2021-08-30 16:48 UTC, merged