Alternative support for qualifiers
NCATSTranslator/ReasonerAPI pull request #326
Opened 2022-05-05 16:41 UTC by edeutsch

Alternative to #325, based on discussion in #325

2022-05-05 17:08 UTC, vdancik requested changes
Can we be more specific, e.g. type => qualifier_type and value => qualifier_value

2022-05-05 18:03 UTC, vdancik approved these changes

2022-06-01 00:01 UTC, mbrush commented on TranslatorReasonerAPI.yaml
> +        - type
should this read 'qualifier_type_id'

2022-06-01 00:03 UTC, mbrush commented on TranslatorReasonerAPI.yaml
> +            subject_direction, etc).
Consider making the example here consistent with the example of a qualifier_type_id above (where you used 'subject_aspect').  So here, say (e.g. 'expression' or 'abundance' for the qualifier type 'subject_aspect', etc).

2022-06-15 17:26 UTC, edeutsch commented
Closing this proposal in favor of #330

2022-06-15 17:26 UTC, closed without merging