`abstract`, `mixin` and `deprecated` `category` and `predicate` Biolink Model terms
NCATSTranslator/ReasonerAPI pull request #375
Opened 2022-09-23 23:39 UTC by RichardBruskiewich

Clarify documentation concerning use of `abstract`, `mixin` and `deprecated` `category` and `predicate` Biolink Model terms in TRAPI.

2022-09-24 00:28 UTC, edeutsch requested changes
I think reference.md is autogenerated from the yaml, so any changes to reference.md will be lost. These documentation changes need to be made to yaml. and we should first create a 1.4 branch and start working in there before we merge.

2022-09-24 18:58 UTC, RichardBruskiewich commented
Hmm.. OK. @edeutsch, I'll take another run at this.

2022-09-24 19:53 UTC, RichardBruskiewich commented
OK, @edeutsch, I manually transferred the comments that I manually included in the **reference.md**, into the **TranslatorReasonerAPI.yaml** file. I'm leaving those revisions in **reference.md**, since they clarify semantics but don't change the function of the schema in TRAPI 1.3 (no harm in telling folks now, rather than later, right?). The next release cycle will simply overwrite the **reference.md** with essentially the identical comments (just without some of the fancy markdown highlights in the curated version).

2022-10-04 20:35 UTC, edeutsch requested changes
Would you rebase this to the "1.4" branch?

2022-10-05 17:31 UTC, RichardBruskiewich commented
> Would you rebase this to the "1.4" branch?

I've tried doing that. I'm all thumbs with esoteric Git comments, though, so I'm not sure if it worked.

2022-10-05 18:16 UTC, edeutsch commented
I'm thinking that if successful, instead of this:
![image](https://user-images.githubusercontent.com/12707718/194132302-dc07134b-efd7-4e01-bb61-1695355f76bd.png)

we should see that you want to merge into 1.4 instead of `master`

?

If you can't get it to work, I suppose since it's just a documentation change, we could merge it into master with little harm.

2022-10-06 17:19 UTC, edeutsch approved these changes

2022-10-06 18:04 UTC, vdancik approved these changes

2022-10-06 22:48 UTC, edeutsch approved these changes

2022-10-20 16:51 UTC, edgargaticaCU approved these changes

2022-10-20 17:15 UTC, vdancik approved these changes

2022-11-01 23:28 UTC, marcdubybroad approved these changes

2022-11-02 00:32 UTC, kennethmorton approved these changes

2022-11-03 14:22 UTC, MarkDWilliams approved these changes

2022-11-03 16:47 UTC, closed without merging