Refactor of source retrieval provenance model
NCATSTranslator/ReasonerAPI pull request #388
Opened 2023-01-19 01:10 UTC by mbrush

Adding RetrievalSource object (and a reference to it form Edge) to support richer representations of retrieval provenance per #369.

2023-01-19 05:32 UTC, edeutsch reviewed
looks good

2023-01-19 05:32 UTC, edeutsch commented on TranslatorReasonerAPI.yaml
> +          enum:
should these have biolink: prefixes?

2023-01-19 05:33 UTC, edeutsch requested changes
however, the build is failing because you have exceeded the dreaded 79 character limit.

2023-01-19 17:27 UTC, edeutsch commented
super-fussy yamllint is still unhappy with this PR:
```
  875:26    error    trailing spaces  (trailing-spaces)

  877:63    error    trailing spaces  (trailing-spaces)

  878:71    error    trailing spaces  (trailing-spaces)

  879:68    error    trailing spaces  (trailing-spaces)

  881:26    error    trailing spaces  (trailing-spaces)

  1197:72   error    trailing spaces  (trailing-spaces)

  1199:61   error    trailing spaces  (trailing-spaces)

  1201:18   error    trailing spaces  (trailing-spaces)

  1204:74   error    trailing spaces  (trailing-spaces)

  1209:23   error    trailing spaces  (trailing-spaces)

  1212:71   error    trailing spaces  (trailing-spaces)

  1214:70   error    trailing spaces  (trailing-spaces)

  1222:17   error    trailing spaces  (trailing-spaces)

  1224:26   error    trailing spaces  (trailing-spaces)

  1225:68   error    trailing spaces  (trailing-spaces)

  1226:73   error    trailing spaces  (trailing-spaces)

  1227:76   error    trailing spaces  (trailing-spaces)

  1228:73   error    trailing spaces  (trailing-spaces)

  1229:75   error    trailing spaces  (trailing-spaces)

  1231:73   error    trailing spaces  (trailing-spaces)

  1232:69   error    trailing spaces  (trailing-spaces)

  1238:1    error    syntax error: found unexpected end of stream (syntax)
```

2023-01-19 18:10 UTC, edeutsch commented on TranslatorReasonerAPI.yaml
> +          enum:
https://biolink.github.io/biolink-model/docs/primary_knowledge_source.html

2023-01-21 19:55 UTC, edeutsch commented
Automatic checks are still failing. I think the problem is that on line 1124 there is an unclosed quote

2023-01-22 01:35 UTC, edeutsch commented
The automatic build is still failing. The goal would be to ensure that the automatic validation passes.
yamllint is now happy but there are multiple OpenAPI schema violations. I think the easiest way to debug your yaml is to paste the entire yaml document in https://editor.swagger.io/ (after clearing the current content)
That interface is pretty good about showing you the schema problems.

2023-01-28 00:44 UTC, sierra-moxon commented
I fixed the tests for this change in PR #393

2023-01-29 22:08 UTC, closed without merging

2023-01-29 22:12 UTC, mbrush commented
Replaced with PR #393 (in which @sierra-moxon fixed syntax errors that were causing test failures, and made resourceRole an object to reference so that it can leverage biolink enums)